#! /bin/bash
port="80"
if [[ "$1" =~ ^[0-9]+$ ]]; then
port=$1
fi

docker run --rm --init -v "$(pwd):/app" -e PORT="$port" -p "$port":"$port" -w /app --memory=1g --env-file=.env -e NODE_ENV=development node:20-alpine3.20 npm run dev