name: Deploy App

on:
  push:
    branches:
      - main
    paths:
      - '!**/*.md'
  pull_request:
    branches:
      - main
    paths:
      - '!**/*.md'
  workflow_dispatch:
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build App Image
        run: docker build -t "${{ secrets.DOCKER_USERNAME }}/tbot" .
      - name: Upload App Image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push "${{ secrets.DOCKER_USERNAME }}/tbot"
      - name: Run App Image on Server
        run: |
          echo ${{ secrets.SSH_KEY }} > ~/.ssh/id_rsa
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} "bash -s ${{secrets.DOCKER_USERNAME}}" < ./deploy
